export const PROFILE_ACTION_TYPES = {
    PROFILE_LOAD_REQUEST: 'PROFILE_LOAD_REQUEST',
    PROFILE_LOAD_SUCCESS: 'PROFILE_LOAD_SUCCESS',
    PROFILE_LOAD_FAIL: 'PROFILE_LOAD_FAIL',
    PROFILE_CHANGE_TAB: 'PROFILE_CHANGE_TAB',

    PROFILE_UPDATE_DESCRIPTION_REQUEST: 'PROFILE_UPDATE_DESCRIPTION_REQUEST',
    PROFILE_UPDATE_DESCRIPTION_SUCCESS: 'PROFILE_UPDATE_DESCRIPTION_SUCCESS',
    PROFILE_UPDATE_DESCRIPTION_FAIL: 'PROFILE_UPDATE_DESCRIPTION_FAIL', 

    PROFILE_RELOAD_AFTER_DELETE: 'PROFILE_RELOAD_AFTER_DELETE',
    POSTS_RELOAD_AFTER_CREATE: 'POSTS_RELOAD_AFTER_CREATE',
    POSTS_RELOAD_AFTER_EDIT: 'POSTS_RELOAD_AFTER_EDIT'
} as const;
