export const EDIT_PROFILE_ACTION_TYPES = {
    EDIT_PROFILE_OPEN: 'EDIT_PROFILE_OPEN',
    EDIT_PROFILE_CLOSE: 'EDIT_PROFILE_CLOSE',
    EDIT_PROFILE_UPDATE_REQUEST: 'EDIT_PROFILE_UPDATE_REQUEST',
    EDIT_PROFILE_UPDATE_SUCCESS: 'EDIT_PROFILE_UPDATE_SUCCESS',
    EDIT_PROFILE_UPDATE_FAIL: 'EDIT_PROFILE_UPDATE_FAIL',
} as const;