// Actions для учетной записи
export const SETTINGS_ACCOUNT_ACTION_TYPES = {
    SETTINGS_ACCOUNT_LOAD_REQUEST: 'SETTINGS_ACCOUNT_LOAD_REQUEST',
    SETTINGS_ACCOUNT_LOAD_SUCCESS: 'SETTINGS_ACCOUNT_LOAD_SUCCESS',
    SETTINGS_ACCOUNT_LOAD_FAIL: 'SETTINGS_ACCOUNT_LOAD_FAIL',
    
    SETTINGS_ACCOUNT_UPDATE_REQUEST: 'SETTINGS_ACCOUNT_UPDATE_REQUEST',
    SETTINGS_ACCOUNT_UPDATE_SUCCESS: 'SETTINGS_ACCOUNT_UPDATE_SUCCESS',
    SETTINGS_ACCOUNT_UPDATE_FAIL: 'SETTINGS_ACCOUNT_UPDATE_FAIL',

    ACCOUNT_DELETE_REQUEST: 'ACCOUNT_DELETE_REQUEST',
    ACCOUNT_DELETE_SUCCESS: 'ACCOUNT_DELETE_SUCCESS',
    ACCOUNT_DELETE_FAIL: 'ACCOUNT_DELETE_FAIL',
} as const;

// Actions для главной страницы настроек
export const SETTINGS_MAIN_ACTION_TYPES = {
    SETTINGS_CHANGE_TAB: 'SETTINGS_CHANGE_TAB'
} as const;

// Actions для уведомлений
export const SETTINGS_NOTIFICATIONS_ACTION_TYPES = {
    SETTINGS_NOTIFICATIONS_LOAD_REQUEST: 'SETTINGS_NOTIFICATIONS_LOAD_REQUEST',
    SETTINGS_NOTIFICATIONS_LOAD_SUCCESS: 'SETTINGS_NOTIFICATIONS_LOAD_SUCCESS',
    SETTINGS_NOTIFICATIONS_LOAD_FAIL: 'SETTINGS_NOTIFICATIONS_LOAD_FAIL',
    
    SETTINGS_NOTIFICATIONS_UPDATE_REQUEST: 'SETTINGS_NOTIFICATIONS_UPDATE_REQUEST',
    SETTINGS_NOTIFICATIONS_UPDATE_SUCCESS: 'SETTINGS_NOTIFICATIONS_UPDATE_SUCCESS',
    SETTINGS_NOTIFICATIONS_UPDATE_FAIL: 'SETTINGS_NOTIFICATIONS_UPDATE_FAIL',
} as const;

// Actions для конфиденциальности
export const SETTINGS_PRIVACY_ACTION_TYPES = {
    SETTINGS_PRIVACY_LOAD_REQUEST: 'SETTINGS_PRIVACY_LOAD_REQUEST',
    SETTINGS_PRIVACY_LOAD_SUCCESS: 'SETTINGS_PRIVACY_LOAD_SUCCESS',
    SETTINGS_PRIVACY_LOAD_FAIL: 'SETTINGS_PRIVACY_LOAD_FAIL',
    
    SETTINGS_PRIVACY_UPDATE_REQUEST: 'SETTINGS_PRIVACY_UPDATE_REQUEST',
    SETTINGS_PRIVACY_UPDATE_SUCCESS: 'SETTINGS_PRIVACY_UPDATE_SUCCESS',
    SETTINGS_PRIVACY_UPDATE_FAIL: 'SETTINGS_PRIVACY_UPDATE_FAIL',
} as const;