export const SETTINGS_ACCOUNT_ACTION_TYPES = {
    SETTINGS_ACCOUNT_LOAD_REQUEST: 'SETTINGS_ACCOUNT_LOAD_REQUEST',
    SETTINGS_ACCOUNT_LOAD_SUCCESS: 'SETTINGS_ACCOUNT_LOAD_SUCCESS',
    SETTINGS_ACCOUNT_LOAD_FAIL: 'SETTINGS_ACCOUNT_LOAD_FAIL',
    
    SETTINGS_ACCOUNT_UPDATE_REQUEST: 'SETTINGS_ACCOUNT_UPDATE_REQUEST',
    SETTINGS_ACCOUNT_UPDATE_SUCCESS: 'SETTINGS_ACCOUNT_UPDATE_SUCCESS',
    SETTINGS_ACCOUNT_UPDATE_FAIL: 'SETTINGS_ACCOUNT_UPDATE_FAIL',

    ACCOUNT_DELETE_REQUEST: 'ACCOUNT_DELETE_REQUEST',
    ACCOUNT_DELETE_SUCCESS: 'ACCOUNT_DELETE_SUCCESS',
    ACCOUNT_DELETE_FAIL: 'ACCOUNT_DELETE_FAIL',
} as const;

export const SETTINGS_AVATAR_ACTION_TYPES = {
    AVATAR_UPLOAD_REQUEST: 'AVATAR_UPLOAD_REQUEST',
    AVATAR_UPLOAD_SUCCESS: 'AVATAR_UPLOAD_SUCCESS',
    AVATAR_UPLOAD_FAIL: 'AVATAR_UPLOAD_FAIL',
    
    AVATAR_DELETE_REQUEST: 'AVATAR_DELETE_REQUEST',
    AVATAR_DELETE_SUCCESS: 'AVATAR_DELETE_SUCCESS',
    AVATAR_DELETE_FAIL: 'AVATAR_DELETE_FAIL',
    
    COVER_UPLOAD_REQUEST: 'COVER_UPLOAD_REQUEST',
    COVER_UPLOAD_SUCCESS: 'COVER_UPLOAD_SUCCESS',
    COVER_UPLOAD_FAIL: 'COVER_UPLOAD_FAIL',
    
    COVER_DELETE_REQUEST: 'COVER_DELETE_REQUEST',
    COVER_DELETE_SUCCESS: 'COVER_DELETE_SUCCESS',
    COVER_DELETE_FAIL: 'COVER_DELETE_FAIL',
} as const;

export const SETTINGS_MAIN_ACTION_TYPES = {
    SETTINGS_CHANGE_TAB: 'SETTINGS_CHANGE_TAB'
} as const;

export const SETTINGS_NOTIFICATIONS_ACTION_TYPES = {
    SETTINGS_NOTIFICATIONS_LOAD_REQUEST: 'SETTINGS_NOTIFICATIONS_LOAD_REQUEST',
    SETTINGS_NOTIFICATIONS_LOAD_SUCCESS: 'SETTINGS_NOTIFICATIONS_LOAD_SUCCESS',
    SETTINGS_NOTIFICATIONS_LOAD_FAIL: 'SETTINGS_NOTIFICATIONS_LOAD_FAIL',
    
    SETTINGS_NOTIFICATIONS_UPDATE_REQUEST: 'SETTINGS_NOTIFICATIONS_UPDATE_REQUEST',
    SETTINGS_NOTIFICATIONS_UPDATE_SUCCESS: 'SETTINGS_NOTIFICATIONS_UPDATE_SUCCESS',
    SETTINGS_NOTIFICATIONS_UPDATE_FAIL: 'SETTINGS_NOTIFICATIONS_UPDATE_FAIL',
} as const;

export const SETTINGS_PRIVACY_ACTION_TYPES = {
    SETTINGS_PRIVACY_LOAD_REQUEST: 'SETTINGS_PRIVACY_LOAD_REQUEST',
    SETTINGS_PRIVACY_LOAD_SUCCESS: 'SETTINGS_PRIVACY_LOAD_SUCCESS',
    SETTINGS_PRIVACY_LOAD_FAIL: 'SETTINGS_PRIVACY_LOAD_FAIL',
    
    SETTINGS_PRIVACY_UPDATE_REQUEST: 'SETTINGS_PRIVACY_UPDATE_REQUEST',
    SETTINGS_PRIVACY_UPDATE_SUCCESS: 'SETTINGS_PRIVACY_UPDATE_SUCCESS',
    SETTINGS_PRIVACY_UPDATE_FAIL: 'SETTINGS_PRIVACY_UPDATE_FAIL',
} as const;
