export const USER_LIST_ACTION_TYPES = {
  USER_LIST_LOAD_REQUEST: 'USER_LIST_LOAD_REQUEST',
  USER_LIST_LOAD_SUCCESS: 'USER_LIST_LOAD_SUCCESS',
  USER_LIST_LOAD_FAIL: 'USER_LIST_LOAD_FAIL',
} as const;

export type UserListActionType = typeof USER_LIST_ACTION_TYPES[keyof typeof USER_LIST_ACTION_TYPES];