export const STATISTICS_ACTION_TYPES = {
    STATISTICS_LOAD_REQUEST: 'STATISTICS_LOAD_REQUEST',
    STATISTICS_LOAD_SUCCESS: 'STATISTICS_LOAD_SUCCESS',
    STATISTICS_LOAD_FAIL: 'STATISTICS_LOAD_FAIL',
    
    SUPPORT_REQUESTS_LOAD_REQUEST: 'SUPPORT_REQUESTS_LOAD_REQUEST',
    SUPPORT_REQUESTS_LOAD_SUCCESS: 'SUPPORT_REQUESTS_LOAD_SUCCESS',
    SUPPORT_REQUESTS_LOAD_FAIL: 'SUPPORT_REQUESTS_LOAD_FAIL',
} as const;